module.exports = {
  BOTTOKEN: "YOUR BOT TOKEN",
  BOTID: "YOUR BOT ID",
  BOTPREFIX: "?",
  BOTOWNERID: ["YOUR ID"],

  DELAY: 1400,
  MAX_DM_PER_COMMAND: 10000,
  EMBEDCOLOR: 0x3498db,
  ERROREMBEDCOLOR: 0xe74c3c,

  PROGRESS_UPDATE_EVERY: 2
};
